import '../model/filter_status.dart';

List<Map> schedules = [
  {
    'img': 'lib/assets/doctor2.png',
    'doctorName': 'Mai Thanh Nam',
    'doctorTitle': 'Bác sĩ tim mạch',
    'reservedDate': 'Thứ 2, 13 tháng 5',
    'reservedTime': '08:00 - 17:00',
    'status': FilterStatus.Upcoming,
    'department': 'Khoa Nội',
  },
  {
    'img': 'lib/assets/doctor2.png',
    'doctorName': 'Nguyễn Lê Lâm',
    'doctorTitle': 'Bác sĩ thần kinh',
    'reservedDate': 'Thứ 4, 15 tháng 5',
    'reservedTime': '08:00 - 17:00',
    'status': FilterStatus.Schedule,
    'department': 'Khoa Thần Kinh',
  },
  {
    'img': 'lib/assets/doctor2.png',
    'doctorName': 'Đinh Văn Tuấn Hải',
    'doctorTitle': 'Bác sĩ ngoại khoa',
    'reservedDate': 'Thứ 3, 14 tháng 5',
    'reservedTime': '08:00 - 17:00',
    'status': FilterStatus.Upcoming,
    'department': 'Khoa Ngoại',
  },
  {
    'img': 'lib/assets/doctor2.png',
    'doctorName': 'Thạch Xuân Hoàng',
    'doctorTitle': 'Bác sĩ nha khoa',
    'reservedDate': 'Thứ 4, 15 tháng 5',
    'reservedTime': '08:00 - 17:00',
    'status': FilterStatus.Upcoming,
    'department': 'Khoa Nha Khoa',
  },
  {
    'img': 'lib/assets/doctor2.png',
    'doctorName': 'Hồ Huy',
    'doctorTitle': 'Bác sĩ da liễu',
    'reservedDate': 'Thứ 5, 16 tháng 5',
    'reservedTime': '08:00 - 17:00',
    'status': FilterStatus.Complete,
    'department': 'Khoa Da Liễu',
  },
  {
    'img': 'lib/assets/doctor2.png',
    'doctorName': 'Nguyễn Đào Anh Tuấn',
    'doctorTitle': 'Bác sĩ răng hàm mặt',
    'reservedDate': 'Thứ 4, 15 tháng 5',
    'reservedTime': '08:00 - 17:00',
    'status': FilterStatus.Upcoming,
    'department': 'Khoa Răng Hàm Mặt',
  },
];
